plugins {
	id 'fabric-loom' version '1.1-SNAPSHOT'
	id 'maven-publish'
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = project.archives_base_name
version = "${project.mod_version}"
group = project.maven_group

sourceSets.main.resources.srcDirs += ['src/main/generated']

repositories {
	maven {
		name "GeckoLib"
		url "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
	}

	maven {
		name "Player Animator"
		url "https://maven.kosmx.dev/"
	}

	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}

	maven {
		name = "Ladysnake"
		url = "https://ladysnake.jfrog.io/artifactory/mods"
	}
	maven {
		url = "https://jitpack.io"
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// Geckolib
	modImplementation "software.bernie.geckolib:geckolib-fabric-1.19:${project.geckolib}"

	//Player Anim
	modImplementation("dev.kosmx.player-anim:player-animation-lib-fabric:${project.player_anim}")

	//MidnightLib
	modImplementation include("maven.modrinth:midnightlib:${project.midnightlib_version}-fabric")

	//Satin
	modImplementation include("io.github.ladysnake:satin:${project.satin_version}")

	// MixinExtras
	implementation("com.github.LlamaLad7:MixinExtras:0.1.1")
	implementation include("com.github.LlamaLad7:MixinExtras:0.1.1")
	annotationProcessor("com.github.LlamaLad7:MixinExtras:0.1.1")

	runtimeOnly('org.joml:joml:1.10.4')
	modRuntimeOnly("maven.modrinth:sodium:${project.sodium}")
	modImplementation "com.ptsmods:devlogin:3.2.2" // To login into your Minecraft account
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}"}
	}
}

loom {
	accessWidenerPath = file("src/main/resources/jcraft.accesswidener")
	runs {
		datagen {
			server()

			name "Minecraft Data"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"

			runDir "build/datagen"
		}
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}

assemble.dependsOn runDatagen
