plugins {
	id 'fabric-loom' version '1.2-SNAPSHOT'
	id 'maven-publish'
	id 'io.freefair.lombok' version '8.4'
}

archivesBaseName = project.archives_base_name
version = "${project.mod_version}"
group = project.maven_group

sourceSets.main.resources.srcDirs += ['src/main/generated']

repositories {
	// So many damn MAVENS. Just use MavenCentral, y'all.
	maven {
		name = "GeckoLib"
		url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
	}

	maven {
		name = "KosmX's maven"
		url = "https://maven.kosmx.dev/"
	}

	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}

	maven {
		name = "Ladysnake"
		url = "https://maven.ladysnake.org/releases"
	}

	maven {
		url = "https://jitpack.io"
	}

	maven {
		name = "Shedaniel's Maven"
		url = "https://maven.shedaniel.me/"
	}

	maven {
		name = "Terraformers MC Maven"
		url = "https://maven.terraformersmc.com/releases/"
	}

	maven {
		name = "EngineHub"
		url = "https://maven.enginehub.org/artifactory/libs-release"
	}

	mavenCentral()
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// Geckolib
	modImplementation "software.bernie.geckolib:geckolib-fabric-1.19:${project.geckolib}"

	//Player Anim
	modImplementation("dev.kosmx.player-anim:player-animation-lib-fabric:${project.player_anim}")

	//Satin
	modImplementation include("io.github.ladysnake:satin:${project.satin_version}")

	// MixinExtras
	implementation include(annotationProcessor("com.github.llamalad7.mixinextras:mixinextras-fabric:0.2.0-beta.9"))

	compileOnly "com.google.guava:guava:32.1.2-jre" // To make TypeToken not 'unstable' :)
	runtimeOnly "org.joml:joml:1.10.4"
	modImplementation "maven.modrinth:sodium:${project.sodium}"
	modImplementation "com.ptsmods:devlogin:3.3.2" // To login into your Minecraft account
	modRuntimeOnly "com.sk89q.worldedit:worldedit-fabric-mc1.19.2:7.2.12"

	// Bendylib
	include modImplementation("io.github.kosmx.bendy-lib:bendy-lib-fabric:${project.bendylib_version}")

	include modImplementation("dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.0.2")
	include modImplementation("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.0.2")

	modApi "com.terraformersmc:modmenu:4.2.0-beta.2"

	modApi("me.shedaniel.cloth:cloth-config-fabric:8.3.103") {
		exclude(group: "net.fabricmc.fabric-api")
	}
}

configurations.all {
	resolutionStrategy {
		force("net.fabricmc:fabric-loader:$loader_version")
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}"}
	}
}

loom {
	accessWidenerPath = file("src/main/resources/jcraft.accesswidener")
	runs {
		datagen {
			inherit client

			name "Data Generation"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
			vmArg "-Dfabric-api.datagen.modid=jcraft"

			runDir "build/datagen"
		}
	}

	splitEnvironmentSourceSets()

	mods {
		"jcraft" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

assemble.dependsOn runDatagen
