# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=1.19.2
	yarn_mappings=1.19.2+build.5
	loader_version=0.14.14

# Mod Properties
	mod_version = 1.19.2-0.10.5
	maven_group = com.example
	archives_base_name = jcraft
	geckolib_core_version=2.0

# Dependencies
	fabric_version=0.75.1+1.19.2
	player_anim=1.0.2
	geckolib=3.1.40